PACKAGE=git_workon
VENV=.venv
NOX_ENV=.nox_env

.PHONY: help
help:
	@echo "venv        -> prepare VENV with all dependencies installed"
	@echo "test        -> run tests"
	@echo "testall     -> run tests for each supported Python version"
	@echo "clean       -> remove autogenerated files (venv, cache, etc.)"
	@echo "coverage    -> run tests coverage and prepare HTML report"
	@echo "build       -> build packages"
	@echo "publish     -> publish packages to the PyPi"


$(VENV):
	poetry install

.PHONY: venv
venv: $(VENV)

.PHONY: test
test: $(VENV)
	poetry run pytest -svvv tests


$(NOX_ENV):
	python3 -m venv $(NOX_ENV)
	$(NOX_ENV)/bin/pip install nox

.PHONY: testall
testall: $(NOX_ENV)
	$(NOX_ENV)/bin/nox

.PHONY: clean
clean:
	rm -rf .venv build _build dist *.egg-info .coverage htmlcov .nox $(NOX_ENV) .python-version
	find . -type f -name '*.py[co]' -delete -o -type d -name __pycache__ -delete
	py3clean . -v

.PHONY: coverage
coverage: $(VENV)
	poetry run pytest --cov-report html --cov=$(PACKAGE) tests/

.PHONY: lint
lint: $(VENV)
	pylint $(PACKAGE) tests
	pydocstyle --ignore=D102,D103,D105,D107,D203,D213 $(PACKAGE)/** tests/**

.PHONY: build
build:
	poetry build

.PHONY: publish
publish: build
	poetry publish
