PACKAGE=git_workon

.PHONY: help
help:
	@echo "venv        -> prepare VENV with all dependencies installed"
	@echo "test        -> run tests"
	@echo "testall     -> run tests for each supported Python version"
	@echo "clean       -> remove autogenerated files (venv, cache, etc.)"
	@echo "coverage    -> run tests coverage and prepare HTML report"
	@echo "build       -> build packages"
	@echo "publish     -> publish packages to the PyPi"

.PHONY: venv
venv:
	poetry install

.PHONY: test
test:
	poetry run pytest -svvv tests

.PHONY: testall
testall:
	pyenv local 3.8.12 3.9.10 3.10.2
	tox -p

.PHONY: clean
clean:
	rm -rf .venv build _build dist *.egg-info .coverage htmlcov .tox .python-version
	find . -type f -name '*.py[co]' -delete -o -type d -name __pycache__ -delete
	py3clean . -v

.PHONY: coverage
coverage:
	poetry run pytest --cov-report html --cov=$(PACKAGE) tests/

.PHONY: lint
lint:
	pylint $(PACKAGE) tests
	pydocstyle --ignore=D102,D103,D105,D107,D203,D213 $(PACKAGE)/** tests/**

.PHONY: build
build:
	poetry build

.PHONY: publish
publish: build
	poetry publish
